### ISSUE TITLE
Missing input files(?)

### ISSUE THREAD

**Issue by kilroyrlc** [Vishal-V/StackGAN#3]
The bird data seems to be missing some files:
./birds/test/
./birds/train/
are both empty and model.py appears to be looking for pickle files.  Is there a preprocessor I should have run?

**Comment by Vishal-V** [comment]
Yes, you have to download the Char-RNN-CNN embeddings from this [download link](https://drive.google.com/file/d/0B3y_msrWZaXLT1BZdVdycDY5TEE) and unzip it in place.
